# Daten vorbereiten

In [96]:
#!pip install sklearn

In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Daten importieren und kennenlernen

In [98]:
dataset = pd.read_csv("data/dataset.csv")

In [99]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Land     10 non-null     object 
 1   Alter    9 non-null      float64
 2   Gehalt   9 non-null      float64
 3   gekauft  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [100]:
dataset

Land  Alter   Gehalt gekauft
0    Frankreich   44.0  72000.0    Nein
1  Griechenland   27.0  48000.0      Ja
2   Deutschland   30.0  54000.0    Nein
3  Griechenland   38.0  61000.0    Nein
4   Deutschland   40.0      NaN      Ja
5    Frankreich   35.0  58000.0      Ja
6  Griechenland    NaN  52000.0    Nein
7    Frankreich   48.0  79000.0      Ja
8   Deutschland   50.0  83000.0    Nein
9    Frankreich   37.0  67000.0      Ja

In [101]:
dataset.head()

Land  Alter   Gehalt gekauft
0    Frankreich   44.0  72000.0    Nein
1  Griechenland   27.0  48000.0      Ja
2   Deutschland   30.0  54000.0    Nein
3  Griechenland   38.0  61000.0    Nein
4   Deutschland   40.0      NaN      Ja

## Featurematrix auswählen

Wir bestimmen das Set von unabhängigen Variablen.



Wir wählen mit `[:, :-1]` aus, dass wir alle Zeilen wollen (`[:, ...]`) und alle Spalten **ohne** die letzte (`[..., :-1]`).

In [102]:
X = dataset.iloc[:, :-1].values

In [103]:
print(X)

[['Frankreich' 44.0 72000.0]
 ['Griechenland' 27.0 48000.0]
 ['Deutschland' 30.0 54000.0]
 ['Griechenland' 38.0 61000.0]
 ['Deutschland' 40.0 nan]
 ['Frankreich' 35.0 58000.0]
 ['Griechenland' nan 52000.0]
 ['Frankreich' 48.0 79000.0]
 ['Deutschland' 50.0 83000.0]
 ['Frankreich' 37.0 67000.0]]


In [104]:
#X.info()

In [105]:
y = dataset.iloc[:, -1].values

In [106]:
print(y)

['Nein' 'Ja' 'Nein' 'Nein' 'Ja' 'Ja' 'Nein' 'Ja' 'Nein' 'Ja']


## Fehlende Daten berücksichtigen

In [107]:


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [108]:
print(X)

[['Frankreich' 44.0 72000.0]
 ['Griechenland' 27.0 48000.0]
 ['Deutschland' 30.0 54000.0]
 ['Griechenland' 38.0 61000.0]
 ['Deutschland' 40.0 63777.77777777778]
 ['Frankreich' 35.0 58000.0]
 ['Griechenland' 38.77777777777778 52000.0]
 ['Frankreich' 48.0 79000.0]
 ['Deutschland' 50.0 83000.0]
 ['Frankreich' 37.0 67000.0]]


## Kategorien in den Daten kodieren

### Die unabhängigen Variablen kodieren (Länderspalte)

In [109]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [110]:
print(X)

[[0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 37.0 67000.0]]


### Die abhängige Variable kodieren

In [111]:


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [112]:
print(y)

[1 0 1 1 0 0 1 0 1 0]


## Daten aufteilen in Training- und Testset

In [113]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [114]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 35.0 58000.0]]


In [115]:
print(X_test)

[[1.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 37.0 67000.0]]


In [116]:
print(y_train)

[1 0 1 1 0 0 1 0]


In [117]:
print(y_test)

[1 0]


## Feature Scaling

In [118]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [119]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 1.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [0.0 1.0 0.0 1.1475343068237058 1.232653363453549]
 [1.0 0.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [120]:
print(X_test)

[[1.0 0.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 -0.44973664397484414 0.2056403393225306]]


## Trainieren des Modells

In [121]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [132]:
new_data = [0.0, 0.0, 1.0, 39, 160000]

In [123]:
print(new_data)

[0.0, 0.0, 1.0, 39, 160000]


In [124]:
new_data = np.array(new_data)

In [125]:
print(new_data)

[0.0e+00 0.0e+00 1.0e+00 3.9e+01 1.6e+05]


In [126]:
new_data = new_data.reshape(1, -1)

In [127]:
print(new_data)

[[0.0e+00 0.0e+00 1.0e+00 3.9e+01 1.6e+05]]


In [128]:
new_data[:, 3:]

array([[3.9e+01, 1.6e+05]])

In [129]:
new_data[:, 3:] = sc.transform(new_data[:, 3:])

In [130]:
print(new_data)

[[ 0.          0.          1.         -0.15932374  8.16499128]]


In [131]:
classifier.predict(new_data)

array([1])