# Übungen zu NumPy

## Importiere das Paket NumPy als np

In [1]:
import numpy as np

## Erzeuge ein Array, dass 10 Einsen enthält

In [2]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Erzeuge ein Array mit 10 Nullen

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Erzeuge ein Array mit 10 Zehnern

In [4]:
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

## Erzeuge ein Array, dass die Zahlen von 10 bis 50 enthält

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## Erzeuge eine 3x3 Matrix mit den Einträgen 1 bis 9

In [6]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Generiere eine Zufallszahl zw. 0 und 1

In [8]:
np.random.rand(1)

array([0.73193565])

## Generiere 16 standardnormalverteilte Zufallszahlen

In [10]:
np.random.randn(16)

array([ 0.78038051, -0.20548831, -0.18281035,  0.28379401, -0.10457846,
       -0.25612981,  0.53566549, -0.50909734, -1.895155  , -1.94767234,
       -0.92500307,  0.06074363,  0.64435418,  1.17679102, -0.72067391,
        1.21046573])

## Wandle den Zufallsvektor in eine 4x4 Matrix um (erneut generieren)

In [11]:
np.random.randn(16).reshape(4,4)

array([[-1.99405482,  0.17411572,  0.87594882, -1.85304982],
       [-0.56228198, -0.7738185 , -1.58244863,  0.33540725],
       [-1.16008668,  0.60549032,  0.99422634, -2.30082968],
       [ 0.2354034 , -1.19083768,  1.1009253 , -0.90919368]])

## Für die Schnellen :) Erzeuge die folgende Matrix
__Hinweis__: man muss eine Division  "/" nutzen!

In [12]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

## Erzeuge einen Vektor mit 10 Punkten zw. 0 und 1, die jeweils gleichweit voneinander entfernt sind.

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Weitere Übungen

Gegeben sei der Vektor v1. Berechne die geforderten Werte. Die Funktionsweise der entsprechenden Methoden (std, sum, ) soll u. U. in der Hilfe nachgeschlagen werden.

In [31]:
v1 = np.random.randn(50)
v1

array([ 0.86748402,  0.75788441, -0.58326743, -1.72809261, -0.63665964,
        0.94253943, -0.71467251, -1.20924526,  1.92933627,  0.9578305 ,
       -0.19853631, -0.70533736, -0.1138925 ,  0.90247712, -1.72635569,
        0.58851869,  0.42943699, -0.26203193,  1.16840884,  0.40996355,
       -2.21548283, -2.41010182, -1.13748027,  0.1896585 , -0.47208016,
       -0.72458397, -0.59417689,  1.34698997,  0.30418707, -1.10008557,
        1.84042422, -0.78532076,  0.70962127,  1.38047643, -0.81533852,
        1.81019447, -0.17048671,  1.24793378, -0.8810338 , -0.85498951,
       -1.36828803, -0.29454411,  0.18864183,  0.20445961, -0.12990888,
       -0.60885661,  0.33502605,  0.75229264, -1.06997303,  0.05653636])

In [30]:
# Berechen die Summe aller Werte in v1
# Füre untenstehende Zelle nicht aus! Würde zum Verlust der Ausgabe führen.
# Dein Code hier:


In [24]:
v1.sum()

-8.40761193143328

In [25]:
# Berechne die Standardabweichung von v1
# Dein Code hier:


In [27]:
v1.std()

0.9891168934830645

In [28]:
# Berechne den Mittelwert aller Werte in v1
# Dein Code hier:


In [29]:
v1.mean()

-0.1681522386286656